language: node_js
node_js:
- '8'
before_install:
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
- npm install jsdoc publish-if-needed npm@latest -g
install:
- npm install jsdoc -g
- npm install
script:
- "./ci/build.js"
- "./ci/shim.js"
- "./ci/test.js"
after_success:
- publish-if-needed
env:
  global:
  - secure: uzbXG1LwPh6+EAMhbWJdTGNzG/OWpyXhzD4A4W4TPt0OyeD2KY+BVU/Quc9b4cZSEjmgN1iIswBtYmv7614KMQVOHBLV1f7C+sTfEFrEuAF/gfWB7uk2T/vahMdjQ24wxkUE2Dl6OguqvBlfRqsLBX97PRUMquAiLF/t7xQ1Iq270DBxAN6iVkQizsf9z12mmI5ocLNsuDfq6Xpf283DUPtfaVoLvCDiYThUxkingGA6KJAhXVRWlYwmQ/74Tq7Yxn3+RRy+9E+L6HpwrwaAeFMB4IFuTIg8TGRhyEd3E6a5j2W5ZpG0k14lrOLfYGcecpvHJt3FfrAKRP4x7HPcHn5flJziJp7m+XK8bp6oXSS4U2zFvHNE81rNo90uuaRSfzKsuk6r4tlwyvcd5vWxZpaJ34K0ZEkkbl6HXW6P+LsPpS4UPDYTxMtm5JXMWrmIMnIxnWMnqNuvKFIkSm3oGApG3sNnA+V8cw8CqEoYSx4WuKo6tqw8wPgVmcpIf0XfdQPBE7+xGpQHYORGrzIrDKNHE4DmBaHtfWjrm8AznI3dKcGdbxw3b084Nxela8gzgimyeWPSfbNzHAbkJ1G/IEQEskbZM/vKGeCNTco4l7DO+h5z+iaa7nvixf2dOB0/jtlFquQEpmFdbSriwPy6+Tg+SU5UaFht0b8T9oLdqzM=
  - secure: YDycLHTJAnLa5lw7/lVGH7kEVFwBRnQ2TG1hinSlczWvM7rlnWQKNpwAB9ySGuTvMNZ0XgNFlCInocsKt9YM3IapVqdCz7vreVuEm8x2meU38x65X8ElmLa2Kh6lLYQEraKL/s/51IPYvAJRzYrWlqN5d819Gn1oEm2EjJCQ5cvznf9kNEXc9SAtqhrCpfiUS51b/OXPS64xyy7PgAA+UbUOUXZC2LP+ebM7X7tS3c/mWEJsz+2Gc22FdoaSFSk5SXG07xiCxeJRLO4i7SfxwkMiDgWoeHuhyGsl2MQVnUoJUtcgLmqLRb/Fpv3wMPSPYsJ/ECLinFMU2LQaUgdBpId2sfTtrRY77fdIgLNGAq4if5k8MZGKjZiBAAvLGqheQlImVGZliydArkRUS2KhKtENOKbaEhKA+yyKxhyyy1IWR1/5OSe1fcVhDSaaFjyONYlr6PtZzorXI1EYss41m2zl5BlmTbjHgK4GA44yZ6+zAqKJjg8Und7n5Li6yXjb6igJcXiBs87Mhj3+jIe3qYeX5zsqDIapivkSZVWYmQK6UMrHV13EA4KmqEl5WlV2dyCuh+tNrwTUKh/U3X+VGjrcfOstSMD/gFySiBPlnJLRa/JPBc76uruymHMQdLruBQVjRjIMjifAbRSsaDFfi8L0w+A6ZkQkUo+PixTiEik=
