language: node_js
node_js:
- '6'
before_install:
# TODO OSS
# - npm i npm-cli-login -g
# - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
# - npm who
- echo "registry = https://realglobe.artifactoryonline.com/realglobe/api/npm/npm-virtual" > $HOME/.npmrc
- curl -u${NPM_USER}:${NPM_PASSWORD} "https://realglobe.artifactoryonline.com/realglobe/api/npm/auth" >> $HOME/.npmrc
- cat $HOME/.npmrc
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "FtWUw7rUls2lpdKP6xFzKPaLvz1z+hhBggshYBXU5hagMl+FUsnvrUim/OBkd3JvdlE0GzvJ899gJy98+4tXqfTfesS9wRcy6vpfN5klt1r7AmeFM0gelDenNHx2UqmzvclWw+0KGYvGOqcx5VJGd0Do17T5m5SOw43O2SiUD8TIOTNeurvab0hJHS6Xo4PzcfiPFTy2ssyrqS2ksT+Tyiw63ius0ghWjQhOhiDgmqk+oKHdumfnwi4oXcv9tAVglquP+orShCyDlQPPNCOEIf/NVIVeG9/Lwk3kAJIfcxOZ6MWhj98VwqDgxsBnKcpfbcYFZm/asG9XhRcxRkkANy7dexD5Zu4QzxQQ7+9XgCx69lDLEvhBZvbhZ+m4Wk5aAi8F14u2gJFOliuJVPmumyM2o9XzV1J2FadVYl1eHLhFPe/qwxM5JX3/XgSGpYJLcDwURz2IQkajDv/TG8u/I8ilqRlgdniv0VzVMs4HG+1qIlL2aIgRXsVUSBzDYi3Psf/lh5RwzSX0pdF1m8858Fhh2V12ZVddj2aOpZahfJevPjZG9qEdO4a+i5NDwA4Utj531XekLj1ZGgfu7UBn8C6SGJY2LAIL7mTN0qDunM9Ao1z3ZrBqG/k/gidMyIYR6EBC2nIZovnRNsUshZdGN2do1RJOMXxQvDEyda0r94I="
